# This line should *not* be indented
publish_mode: editorial_workflow

backend:
  name: git-gateway
  branch: master
  repo: Nelogy92/gatsby-first

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{ slug }}'
    fields:
      - { label: 'Team member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
