# This line should *not* be indented
publish_mode: editorial_workflow

backend:
  name: github
  branch: master
  repo: Neology92/gatsby-first

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{ slug }}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
    card: { type: 'alltype', text: 'title' }

  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{ slug }}'
    fields:
      - { label: 'Team member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
    card: { type: 'alltype', text: 'title' }
